import { normalizeAssetPath } from "../lib/assets";

const buildDescription = (lines) => lines.join("\n");

const buildProject = ({
  id,
  title,
  category,
  role,
  year,
  images = [],
  captions = [],
  descriptionLines,
  tags = [],
  links = [],
}) => ({
  id,
  title,
  category,
  role,
  year,
  images: images.map((path) => normalizeAssetPath(path)),
  captions,
  description: buildDescription(descriptionLines),
  tags,
  links,
});

export const projects = [
  buildProject({
    id: "nalda2",
    title: "NALDA - 2",
    category: "600m-Class Sounding Rocket",
    role: "Team Leader & Propulsion Module Developent",
    year: "2023",
    images: [
      "/images/nalda2/nalda2_main.png",
      "/images/nalda2/nalda2_rocket.jpg",
      "/images/nalda2/nalda2_srm.jpg",
      "/images/nalda2/nalda2_rocket_modeling.png",
      "/images/nalda2/nalda2_rocket_motor_modeling.png",
      "/images/nalda2/nadla2_grain_manufacturing.jpg",
    ],
    descriptionLines: [
      "- My First Rocket Engine Test & Flight",
      "- Sounding Rocket with I Class KNSB Motor",
      "- A thrilling flight test (Don't try this at home)",
    ],
    tags: ["SRM", "KNSB", "Sounding Rocket"],
    links: [
      {
        name: "[Youtube] Static Fire",
        url: "https://youtu.be/y-Bl1bwOfSU?si=TM1PpCnROWI0t8S_",
      },
      {
        name: "[Youtube] Test Flight",
        url: "https://youtu.be/ZTEYskIgb0E",
      },
    ],
  }),
  buildProject({
    id: "pallas_mini",
    title: "Pallas Mini",
    category: "Flight Proven I-Class KNSB Motor",
    role: "Propulsion System Development",
    year: "2024",
    images: [
      "/images/pallas_mini/pallas_mini_main.png",
      "/images/pallas_mini/pallas_mini_thrust_curve.png",
      "/images/pallas_mini/pallas_mini_after_static_fire.jpg",
      "/images/pallas_mini/pallas_mini_cross_section2.png",
      "/images/pallas_mini/pallas_mini_cross_section.png",
      "/images/pallas_mini/pallas_mini_view.png",
    ],
    descriptionLines: [
      "- I-Class KNSB motor for AJOURO's Sounding Rocket",
      "- Multi-Segment Design for Netural Thrust Curve",
      "- Maximizing performance by weight-optimized design",
      "(Total 1kg including propellant, about 40% propellant loading fraction)",
      "- Thrust Efficiency > 92% (ISP: 107 sec at SL)",
    ],
    tags: ["SRM", "KNSB", "Multi Segment", "Flight Proven"],
    links: [
      {
        name: "[Youtube] Static Fire",
        url: "https://youtu.be/1du52inQEJk",
      },
      {
        name: "[Instagram] Thrust Curve",
        url: "https://www.instagram.com/p/C9tLrcHyIy7/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      },
      {
        name: "Design File",
        url: "#",
      },
    ],
  }),
  buildProject({
    id: "ajr1",
    title: "AJR - 1",
    category: "400m-Class Sounding Rocket at 2024 NURA",
    role: "Propulsion System Development & Total System Advisor",
    year: "2024",
    images: [
      "/images/ajr1/ajr1_main.jpg",
      "/images/ajr1/ajr1_sub1.png",
      "/images/ajr1/ajr1_sub2.png",
      "/images/ajr1/ajr1_sub3.jpg",
      "/images/ajr1/ajr1_sub4.jpg",
      "/images/ajr1/ajr1_sub5.png",
      "/images/ajr1/ajr1_sub7.jpg",
    ],
    descriptionLines: [
      "- 400m Class Sounding Rocket Developed at AJOURO",
      "- Successfully Launched & Recovered at NURA 2024",
      "- Pixhawk based Avionics System",
      "- Survo motor based Fairing open type Recovery System",
      "- Successfully Recovered after reaching about 250m",
    ],
    tags: ["NURA", "AJOURO", "Sounding Rocket", "SRM"],
    links: [
      {
        name: "[Youtube] Flight Video",
        url: "https://youtu.be/f6b4FRlGqX4",
      },
      {
        name: "[Shorts] Flight Video",
        url: "https://youtube.com/shorts/ARVEHhoLQ3k?si=o92ngrxS1qNRs1OR",
      },
      {
        name: "[Univ News] Award News",
        url: "https://www.ajou.ac.kr/kr/ajou/studentNews.do?mode=view&articleNo=341386&article.offset=0&articleLimit=12",
      },
    ],
  }),
  buildProject({
    id: "helios03",
    title: "Helios 0.3",
    category: "3kN LOX/Kerosene Combustor with Regen Cooling",
    role: "Developer",
    year: "2024",
    images: ["/images/helios03/helios03_main.jpg"],
    descriptionLines: [
      "- 3kN LOX/Kerosene Combustor",
      "- Additively Manufactured by PBF",
      "- Display model with STS316L and IN718 for Development model",
    ],
    tags: ["LOX", "Kerosene", "Regenerative Cooling", "AM"],
    links: [
      {
        name: "Design File",
        url: "#",
      },
    ],
  }),
  buildProject({
    id: "asi",
    title: "GOX/GCH4 ASI",
    category: "GOX/GCH4 ASI for Helios 0.3",
    role: "PM",
    year: "2025",
    images: [
      "/images/30n_asi/30n_asi_main.jpg",
      "/images/30n_asi/30n_asi_sub1.jpg",
    ],
    descriptionLines: [
      "- GOX/GCH4",
      "- Gas based Augmented Spark Ignitor",
      "- Developed & Tested for 3kN LOX/Kerosene LRE",
      "- One-piece, billet-machined design for reduced lead time and faster iteration.",
    ],
    tags: ["ASI", "GOX", "GCH4"],
    links: [
      {
        name: "Static Test",
        url: "https://youtu.be/Z7pxDd2Fwcc",
      },
    ],
  }),
  buildProject({
    id: "ajr2",
    title: "AJR - 2",
    category: "400m-Class Sounding Rocket at 2025 NURA",
    role: "Propulsion System Development & Total System Advisor",
    year: "2024",
    images: [
      "/images/ajr2/ajr2_main.jpg",
      "/images/ajr2/ajr2_sub1.jpg",
      "/images/ajr2/ajr2_sub2.png",
      "/images/ajr2/ajr2_sub3.jpg",
      "/images/ajr2/ajr2_sub4.jpg",
      "/images/ajr2/ajr2_sub5.png",
    ],
    descriptionLines: [
      "- 400m Class Sounding Rocket Developed at AJOURO",
      "- Weight reduction and improved operability through optimized design.",
      "- Successfully Launched & Recovered at NURA 2025",
      "- Pixhawk based Avionics System",
      "- Survo motor based Fairing open type Recovery System",
      "- Successfully Recovered after reaching about 380m",
    ],
    tags: ["NURA", "AJOURO", "Sounding Rocket", "SRM"],
    links: [
      {
        name: "[Instagram] Flight Video",
        url: "https://www.instagram.com/reel/DNKYI02hKgk/?utm_source=ig_web_copy_link&igsh=MzRlODBiNWFlZA==",
      },
    ],
  }),
  buildProject({
    id: "pallas_l2000e",
    title: "Pallas - L2000E",
    category: "2kN LOX / Ethanol Combustor",
    role: "Desinger",
    year: "2026",
    images: [
      "/images/pallas_l2000e/pallas_l2000e_main.png",
      "/images/pallas_l2000e/pallas_l2000e_sub1.png",
      "/images/pallas_l2000e/pallas_l2000e_sub2.png",
      "/images/pallas_l2000e/pallas_l2000e_sub3.png",
      "/images/pallas_l2000e/pallas_l2000e_sub4.png",
      "/images/pallas_l2000e/pallas_l2000e_sub5.png",
    ],
    descriptionLines: [
      "- 2kN Ethalox Demo LRE",
      "",
      "- LOX-centered Pintle Injector (Clean-Sheet Design)",
      "",
      "| Item | Value |",
      "|:---:|:---:|",
      "| Thrust | 2000 N (SL) |",
      "| Propellant | LOX/Ethanol |",
      "| Injector | Pintle Injector |",
      "| Cooling | Ablative (Graphite Inner) |",
      "| Chamber Pressure | 15 bar ( 1.5MPa ) |",
      "| Isp (SL) | 206 s |",
      "| Isp (Vac) | 236 s |",
    ],
    tags: ["LOX", "Ethanol", "Pintle Injector", "Ablative Cooling"],
    links: [
      {
        name: "Design File",
        url: "#",
      },
    ],
  }),
  buildProject({
    id: "vulcan_200",
    title: "Vulcan - 200 Project",
    category: "To be revealed in Q2 2026",
    role: "PM",
    year: "2025 - 2026",
    images: ["/images/optic_the_cat.jpg", "/images/optic_the_second_cat.jpg"],
    descriptionLines: [
      "- 200 N GOX / GCH4 Engine",
      "- Gas-Gas Impinging Injector",
      "- Additive Manufactured with IN718",
    ],
    tags: ["GOX", "GCH4", "Impinging Injector", "Heat Sink", "AM"],
    links: [
      {
        name: "Design File",
        url: "#",
      },
    ],
  }),
  buildProject({
    id: "pallas_micro_v4",
    title: "Pallas Micro v4",
    category: "H-Class KNSB Motor",
    role: "Desinger",
    year: "2026",
    images: [
      "/images/pallas_micro_v4/pallas_micro_main.png",
      "/images/pallas_micro_v4/pallas_micro_sub1.png",
      "/images/pallas_micro_v4/pallas_micro_sub2.png",
      "/images/pallas_micro_v4/pallas_micro_sub3.png",
      "/images/pallas_micro_v4/pallas_micro_sub4.png",
      "/images/pallas_micro_v4/pallas_micro_sub5.png",
      "/images/pallas_micro_v4/pallas_micro_sub6.png",
    ],
    descriptionLines: [
      "- H-Class KNSB Motor",
      "- Neutral Thrust Curve by Multi-Segment Design",
      "- Fail-safe design with a higher chamber FoS and controlled joint release",
      "- Planned for static-fire testing in Q1 2026",
      "",
      "",
      "| Item | Value |",
      "|:---:|:---:|",
      "| Motor Class | H200 |",
      "| Propellant | KNSB |",
      "| Diameter | 38 mm |",
      "| Height | 275 mm |",
      "| Burn Time | 1.1 s |",
      "| Average Thrust | 200 N |",
      "| Total Impulse | 228 N·s |",
      "| Isp | 116 s |",
      "| Propellant Weight | 200 g |",
      "| Total Weight | 530 g |",
      "| Mass Fraction | 38 % |",
      "| Chamber, Clousers, Retainer | Al6061-T6 |",
      "| Nozzle | STS304 |",
      "",
    ],
    tags: ["SRM", "KNSB", "Multi Segment"],
    links: [
      {
        name: "Design File",
        url: "#",
      },
    ],
  }),
  buildProject({
    id: "ALPM",
    title: "ALPM",
    category: "Advanced Light-weight Propulsion Module",
    role: "Propulsion System Development",
    year: "2026",
    images: [
      "/images/alpm/alpm_main.png",
      "/images/alpm/alpm_sub1.png",
      "/images/alpm/alpm_sub2.png",
      "/images/alpm/alpm_sub3.png",
      "/images/alpm/alpm_sub4.png",
    ],
    descriptionLines: [
      "- I-Class KNSB Motor ( derived from Pallas - Mini )",
      "",
      "- Same propellant mass( 400g ), reduced structure mass",
      "- EX60 Carbon Ablative Nozzle ",
      "- Developed for 2026 NURA, single I-Class motor for 800 m apogee",
      "",
      "",
      "| Item | Value |",
      "|:---:|:---:|",
      "| Motor Class | I296 |",
      "| Propellant | KNSB |",
      "| Diameter | 47 mm |",
      "| Height | 305 mm |",
      "| Burn Time | 1.6 s |",
      "| Average Thrust | 296 N |",
      "| Total Impulse | 462 N·s |",
      "| Isp | 116 s |",
      "| Propellant Weight | 400 g |",
      "| Total Weight | < 760 g |",
      "| Mass Fraction | > 53 % |",
      "| Chamber, Closures, Retainer | Al6061-T6 |",
      "| Nozzle | Ablative Liner ( EX60 ) |",
      "",
    ],
    tags: ["SRM", "KNSB", "Ablative Cooling", "AJOURO", "Multi Segment"],
    links: [
      {
        name: "Design File",
        url: "#",
      },
    ],
  }),
];

export const projectsById = Object.fromEntries(
  projects.map((project) => [project.id, project]),
);

export const projectTags = [...new Set(projects.flatMap((project) => project.tags))].sort(
  (left, right) => left.localeCompare(right),
);
